# Generated by Django 4.1.7 on 2023-04-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="libro",
            name="autor",
        ),
        migrations.AddField(
            model_name="libro",
            name="autor_dni",
            field=models.CharField(default="Sin autor", max_length=20),
        ),
    ]
