# Generated by Django 4.1.7 on 2023-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App_biblioteca", "0002_remove_libro_autor_libro_autor_dni"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libro",
            name="autor_dni",
            field=models.CharField(max_length=20),
        ),
    ]
